//! Storage trait for token persistence.
//!
//! `daruma-storage` implements [`TokenStore`] over SQLite. Keeping the
//! trait here lets the verifier and the bootstrap logic live in this crate
//! without pulling sqlx in.

use async_trait::async_trait;
use daruma_shared::{AgentId, DeviceId, Result, TokenId};

use crate::token::ApiToken;

/// Persistence API that the auth middleware/verifier depends on.
///
/// Implementations must be cheap to clone (typically wrap a pool of
/// connections behind an `Arc`).
#[async_trait]
pub trait TokenStore: Send + Sync + 'static {
    /// Insert a freshly-generated token record. Idempotent insert is not
    /// required — IDs are UUIDv7 generated by the caller.
    async fn insert(&self, token: ApiToken) -> Result<()>;

    /// Return every (active or not) token whose `prefix` matches.
    /// Verification of the actual plaintext happens against the candidates'
    /// `hash` field in the middleware; the store is **not** responsible for
    /// filtering revoked/expired rows so that the middleware can return
    /// the most precise diagnostic.
    async fn list_by_prefix(&self, prefix: &str) -> Result<Vec<ApiToken>>;

    /// Lookup a single token by id (used by admin endpoints).
    async fn get(&self, id: TokenId) -> Result<Option<ApiToken>>;

    /// List every token issued for an agent (admin endpoint).
    async fn list_for_agent(&self, agent_id: AgentId) -> Result<Vec<ApiToken>>;

    /// Mark a token as revoked. Returns `false` if the token does not
    /// exist; idempotent for already-revoked tokens.
    async fn revoke(&self, id: TokenId) -> Result<bool>;

    /// Update `last_used_at`. Best-effort; failure is logged but never
    /// fatal for the request being authenticated.
    async fn touch_last_used(&self, id: TokenId) -> Result<()>;

    /// Update the owning device's `last_seen_at`, throttled by the store.
    async fn touch_device_last_seen(&self, id: DeviceId) -> Result<()>;

    /// Count how many non-revoked tokens currently exist (used by bootstrap
    /// logic to decide whether to generate the initial admin token).
    async fn count_active(&self) -> Result<u64>;
}
